version: "3.8"

services:
    tor-tunnel:
        image: whatisl/tor-tunnel:3.6
        container_name: tor-tunnel
        ports:
            - "29000:29000"
        environment:
            PROXY: ""
            TorInstanceNum: 10
        restart: on-failure
